#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

swagger: '2.0'
info:
  version: 1.1.1
  title: EO EVNFM Crypto Interface
  description: >
    EO EVNFM Crypto Interface API guide
basePath: /generic/v1
schemes:
  - https

# Descriptions of common responses
responses:
  NoContent:
    description: >
      No Content

      The request has succeeded with no content in response.
  UnprocessableEntity:
    description: >
      UnprocessableEntity
      If the API consumer request ended with KMS error, that produce UnprocessableEntity
    schema:
      $ref: '#/definitions/ProblemDetails'
  Unauthorized:
    description: >
      Unauthorized
      If the request contains no access token even though one is required,
      or if the request contains an authorization token that is invalid
      (e.g. expired or revoked), the API producer should respond with this
      response. The details of the error shall be returned in the
      WWW-Authenticate HTTP header, as defined in IETF RFC 6750 and IETF
      RFC 7235. The ProblemDetails structure may be provided.
    headers:
      Content-Type:
        description: The MIME type of the body of the response.
        type: string
        maximum: 1
        minimum: 1
    schema:
      $ref: '#/definitions/ProblemDetails'
  Forbidden:
    description: >
      Forbidden
      If the API consumer is not allowed to perform a particular request
      to a particular resource, the API producer shall respond with this
      response code. The "ProblemDetails" structure shall be provided.  It
      should include in the "detail" attribute information about the
      source of the problem, and may indicate how to solve it.
    headers:
      Content-Type:
        description: The MIME type of the body of the response.
        type: string
        maximum: 1
        minimum: 1
    schema:
      $ref: '#/definitions/ProblemDetails'
  InternalServerError:
    description: >
      Internal Server Error
      If there is an application error not related to the client's input
      that cannot be easily mapped to any other HTTP response code ("catch
      all error"), the API producer shall respond withthis response code.
      The "ProblemDetails" structure shall be provided, and shall include
      in the "detail" attribute more information about the source of the
      problem.
    headers:
      Content-Type:
        description: The MIME type of the body of the response.
        type: string
        maximum: 1
        minimum: 1
    schema:
      $ref: '#/definitions/ProblemDetails'
  ServiceUnavailable:
    description: >
      Service Unavailable
      If the API producer encounters an internal overload situation of
      itself or of a system it relies on, it should respond with this
      response code, following the provisions in IETF RFC 7231 [13] for
      the use of the "Retry-After" HTTP header and for the alternative to
      refuse the connection. The "ProblemDetails" structure may be
      omitted.
    headers:
      Content-Type:
        description: The MIME type of the body of the response.
        type: string
        maximum: 1
        minimum: 1
    schema:
      $ref: '#/definitions/ProblemDetails'
definitions:
  ProblemDetails:
    description: >
      The definition of the general "ProblemDetails" data structure from
      IETF RFC 7807 [19] is reproduced in this structure. Compared to
      the general framework defined in IETF RFC 7807 [19], the "status"
      and "detail" attributes are mandated to be included by the present
      document, to ensure that the response contains additional textual
      information about an error. IETF RFC 7807 [19] foresees
      extensibility of the "ProblemDetails" type. It is possible that
      particular APIs in the present document, or particular
      implementations, define extensions to define additional attributes
      that provide more information about the error. The description
      column only provides some explanation of the meaning to Facilitate
      understanding of the design. For a full description, see IETF RFC
      7807 [19].
    type: object
    required:
      - status
      - detail
    properties:
      type:
        description: >
          A URI reference according to IETF RFC 3986 [5] that identifies
          the problem type. It is encouraged that the URI provides
          human-readable documentation for the problem (e.g. using HTML)
          when dereferenced. When this member is not present, its value
          is assumed to be "about:blank".
        type: string
        format: URI
      title:
        description: >
          A short, human-readable summary of the problem type. It should
          not change from occurrence to occurrence of the problem,
          except for purposes of localization. If type is given and
          other than "about:blank", this attribute shall also be
          provided. A short, human-readable summary of the problem
          type.  It SHOULD NOT change from occurrence to occurrence of
          the problem, except for purposes of localization (e.g., using
          proactive content negotiation; see [RFC7231], Section 3.4).
        type: string
      status:
        description: >
          The HTTP status code for this occurrence of the problem. The
          HTTP status code ([RFC7231], Section 6) generated by the
          origin server for this occurrence of the problem.
        type: integer
      detail:
        description: >
          A human-readable explanation specific to this occurrence of
          the problem.
        type: string
      instance:
        description: >
          A URI reference that identifies the specific occurrence of the
          problem. It may yield further information if dereferenced.
        type: string
        format: URI
  URILink:
    description: |
      This type represents a link to a resource.
    type: object
    required:
      - href
    properties:
      href:
        description: |
          URI of the referenced resource.
        type: string
        format: url

paths:
  /keys:
    post:
      description: >
        Update latest key
        The POST method updates latest key.
      responses:
        '204':
          description: Latest Key was updated successfully
        '422':
          $ref: '#/responses/UnprocessableEntity'
        '500':
          $ref: '#/responses/InternalServerError'
        '503':
          $ref: '#/responses/ServiceUnavailable'