#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $keystorePvc := print "keystore-pvc-" ( include "eric-eo-evnfm-crypto.name" . ) "-stateful-set-0" -}}
{{- $persistentVolume := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $keystorePvc) -}}
{{- if $persistentVolume }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-binding
roleRef:
  kind: Role
  name: pvc-delete
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-eo-evnfm-crypto.name" . }}-migration-cleanup-sa
    namespace: {{ .Release.Namespace }}
{{- end }}